---

- name: ({{ os_with_version }}) Install 'which' command if not installed on RedHat based OS
  package:
   name: which
   state: present
  when:
   - ansible_os_family == "RedHat"

- name: ({{ os_with_version }}) Install GIT From Source Tasks Block
  block:

   - name: ({{ os_with_version }}) Enable EPEL Releases
     yum:
      name: epel-release
      state: present
     when:
      - ansible_os_family == "RedHat"

   - name: ({{ os_with_version }}) Ensure require dependencies are installed ({{ git_required_packages }})
     package:
      name: "{{ item }}"
      state: present
     with_items: "{{ git_required_packages }}"

   - name: ({{ os_with_version }}) Create simlink for docbook2x-texi on RedHat based OS
     file:
      src: "/usr/bin/db2x_docbook2texi"
      dest: "/usr/bin/docbook2x-texi"
      state: link
     when:
      - ansible_os_family == "RedHat"

   - name: ({{ os_with_version }}) Create GIT Expand directory ({{ git_tmp_expand_dir }})
     file:
      path: "{{ git_tmp_expand_dir }}"
      state: directory

   - name: ({{ os_with_version }}) Uncompress Git archives to {{ git_tmp_expand_dir }}
     unarchive:
      src: "{{ git_downloaded_file }}"
      dest: "{{ git_tmp_expand_dir }}"
      creates: "{{ git_tmp_expand_dir }}/README"
      remote_src: true
      extra_opts:
       - --strip-components=1

   - name: ({{ os_with_version }}) Ensure that installed dir exists ({{ git_install_dir }})
     file:
      path: "{{ git_install_dir }}"
      state: directory

   - name: ({{ os_with_version }}) Build Git to installed ({{ git_install_dir }}) - ({{ git_build_packages }})
     make:
      target: "{{ item }}"
      chdir: "{{ git_tmp_expand_dir }}"
      params:
       prefix: "{{ git_install_dir }}"
     with_items: "{{ git_build_packages }}"
     changed_when: false
     failed_when: false
     check_mode: false
     register: git_build

   - name: Execute ls
     command: >
      ls -al /usr
     changed_when: false
     failed_when: false
     check_mode: false
     register: usr

   - name: Execute ls
     command: >
      ls -al /usr/bin
     changed_when: false
     failed_when: false
     check_mode: false
     register: usr_bin

   - name: Pring Build Result
     debug:
      var: git_build

   - name: Pring LS usr
     debug:
      var: usr

   - name: Pring LS usr_bin
     debug:
      var: usr_bin

  when:
   - from_source|bool
   - git_process_install|bool

- name: ({{ os_with_version }}) Install GIT From Repository Tasks Block
  block:

   - name: ({{ RedHat }}) Install GIT with additional packages ({{ git_packages }})
     yum:
      name: "{{ git_packages }}"
      state: present
      enablerepo: "{{ git_additionnal_repos }}"
     when:
      - ansible_os_family == "RedHat"
     register: git_install_redhat

   - name: ({{ os_with_version }}) Update APT Cache
     apt:
      update_cache: true
      cache_valid_time: 86400
     when:
      - ansible_os_family == "Debian"

   - name: ({{ Debian }}) Install GIT with addirional packages ({{ git_packages }})
     apt:
      name: "{{ git_packages }}"
      state: present
     when:
      - ansible_os_family == "Debian"
     register: git_install_centos

   - name: ({{ os_with_version }}) Check Just installed GIT version.
     command: >
       which git
     changed_when: false
     failed_when: false
     check_mode: false
     register: just_installed_git_version

   - name: ({{ os_with_version }}) Print install from repository result
     debug:
      var: just_installed_git_version

  when:
   - not from_source|bool
